# Generated by Django 5.0.7 on 2024-07-29 18:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('level', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)])),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('perDiem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('localRunning', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estacode', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assumptionOfDuty', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='hr_app.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OfficialAppointment',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.department')),
                ('gradeLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DRUID_VIEWER', 'Druid Viewer'), ('SUPER_ADMIN', 'Super Admin'), ('DIRECTOR_GENERAL', 'Director General'), ('IT_ADMIN', 'IT Admin'), ('HR_ADMIN', 'HR Admin'), ('MONITORING_OFFICER', 'Monitoring Officer'), ('VERIFICATION_OFFICER', 'Verification Officer'), ('HELPDESK', 'Helpdesk'), ('HR_DATA_SCREENING', 'HR Data Screening')], max_length=20)),
                ('phoneNumber', models.CharField(blank=True, max_length=11)),
                ('ippisNumber', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('allowedDepartments', models.ManyToManyField(blank=True, related_name='allowed_users', to='hr_app.department')),
                ('allowedStates', models.ManyToManyField(blank=True, related_name='allowed_users', to='hr_app.state')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.department')),
                ('stateOfPosting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_users', to='hr_app.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('allowedZones', models.ManyToManyField(blank=True, related_name='allowed_users', to='hr_app.zone')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr_app.zone'),
        ),
    ]
