# Generated by Django 5.0.7 on 2024-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialappointment',
            name='cadre',
            field=models.CharField(choices=[('O', 'OFFICER'), ('E', 'EXECUTIVE'), ('S', 'SECRETARIAL'), ('C', 'CLERICAL'), ('D', 'DRIVER')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='description',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
