# Generated by Django 5.0.7 on 2024-07-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_officialappointment_cadre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialappointment',
            name='code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
