# Generated by Django 5.0.7 on 2024-07-29 21:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_alter_officialappointment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAuditEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ippisNumber', models.CharField(blank=True, max_length=8, null=True)),
                ('fileNumber', models.CharField(blank=True, max_length=8, null=True)),
                ('title', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=50)),
                ('otherNames', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('maritalStatus', models.CharField(blank=True, choices=[('S', 'SINGLE'), ('M', 'MARRIED'), ('D', 'DIVORCED'), ('W', 'WIDOWED')], max_length=1, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('step', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)])),
                ('cadre', models.CharField(blank=True, choices=[('O', 'OFFICER'), ('E', 'EXECUTIVE'), ('S', 'SECRETARIAL'), ('C', 'CLERICAL'), ('D', 'DRIVER')], max_length=1, null=True)),
                ('dateOfFirstAppointment', models.DateField(blank=True, null=True)),
                ('dateOfPresentAppointment', models.DateField(blank=True, null=True)),
                ('dateOfConfirmation', models.DateField(blank=True, null=True)),
                ('isOnLeave', models.BooleanField(default=False)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('accountType', models.CharField(blank=True, choices=[('S', 'Savings'), ('C', 'Current')], max_length=1, null=True)),
                ('pfa', models.CharField(blank=True, max_length=10, null=True)),
                ('pfaNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('nok1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nok1_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('nok1_address', models.CharField(blank=True, max_length=100, null=True)),
                ('nok1_phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('nok2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nok2_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('nok2_address', models.CharField(blank=True, max_length=100, null=True)),
                ('nok2_phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('staffUpdate', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.department')),
                ('gradeLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.gradelevel')),
                ('lgaOfOrigin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lga_of_origin', to='hr_app.lga')),
                ('stateOfOrigin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_of_origin', to='hr_app.state')),
                ('stateOfPosting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_of_posting', to='hr_app.state')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station', to='hr_app.lga')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAuditEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('institution', models.CharField(blank=True, max_length=50, null=True)),
                ('yearOfCertificateObtained', models.DateField(blank=True, null=True)),
                ('monthOfCertificateObtained', models.DateField(blank=True, null=True)),
                ('dayOfCertificateObtained', models.DateField(blank=True, null=True)),
                ('certifucateType', models.CharField(blank=True, choices=[('PSLC', 'Primary School Leaving Certificate'), ('JSCE', 'Junior Secondary School Certificate'), ('SSCE', 'Senior Secondary School Certificate'), ('OND', 'Ordinary National Diploma'), ('HND', 'Higher National Diploma'), ('BSC', 'Bachelor Degree'), ('PGD', 'Postgraduate Diploma'), ('MSC', 'Master Degree'), ('PHD', 'Doctorate Degree'), ('PROF', 'Professional Certification')], max_length=4, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.staffauditemployee')),
            ],
        ),
    ]
