# Generated by Django 5.0.7 on 2024-07-30 04:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialappointment',
            options={'verbose_name': 'Official Appointment', 'verbose_name_plural': 'Official Appointments'},
        ),
        migrations.AddField(
            model_name='employee',
            name='isFlagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='verificationDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='verificationNotes',
            field=models.TextField(blank=True, verbose_name='Verification Notes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='verifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeVerification', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='staffauditemployee',
            name='staffUpdateDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pfaNumber',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$')]),
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancyType', models.CharField(choices=[('DOB', 'Date of Birth'), ('DOF', 'Date of First Appointment'), ('DOP', 'Date of Present Appointment'), ('DOC', 'Date of Confirmation'), ('GL', 'Grade Level'), ('DEPT', 'Department'), ('SOP', 'State of Posting'), ('OTHER', 'Other')], max_length=5)),
                ('auditValue', models.CharField(help_text='Value from StaffAuditEmployee', max_length=255)),
                ('employeeValue', models.CharField(help_text='Value from Employee', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional details about the discrepancy')),
                ('isResolved', models.BooleanField(default=False)),
                ('resolutionDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='hr_app.employee')),
                ('resolvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolvedDiscrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Discrepancies',
            },
        ),
        migrations.CreateModel(
            name='EducationAndTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityType', models.CharField(choices=[('FE', 'Formal Education'), ('PC', 'Professional Certification'), ('SC', 'Short Course'), ('WT', 'Workshop/Training'), ('CO', 'Conference'), ('OT', 'Other')], max_length=2)),
                ('title', models.CharField(help_text='Title of the degree, certification, or course', max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('PSLC', 'Primary School Leaving Certificate'), ('JSCE', 'Junior Secondary School Certificate'), ('SSCE', 'Senior Secondary School Certificate'), ('OND', 'Ordinary National Diploma'), ('HND', 'Higher National Diploma'), ('BSC', 'Bachelor Degree'), ('PGD', 'Postgraduate Diploma'), ('MSC', 'Master Degree'), ('PHD', 'Doctorate Degree'), ('PROF', 'Professional Certification'), ('NA', 'Not Applicable')], max_length=4, verbose_name='Level of Education')),
                ('startDate', models.DateField(verbose_name='Start Date of Program')),
                ('endDate', models.DateField(blank=True, help_text='End date of Program. Leave blank if ongoing', null=True)),
                ('certificateObtained', models.BooleanField(default=False, help_text='Tick if certificate obtained', verbose_name='Certificate Obtained?')),
                ('isVerified', models.BooleanField(default=False)),
                ('verificationDate', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationAndTraining', to='hr_app.employee')),
                ('verifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educationVerifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education and Training Record',
                'verbose_name_plural': 'Education and Training Records',
                'ordering': ['-endDate', '-startDate'],
            },
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Employer Name')),
                ('organisation', models.CharField(max_length=255, verbose_name='Organisation Name')),
                ('position', models.CharField(max_length=255, verbose_name='Position Title')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previousEmployments', to='hr_app.employee')),
            ],
            options={
                'verbose_name': 'Previous Employment',
                'verbose_name_plural': 'Previous Employments',
                'ordering': ['-endDate', '-startDate'],
            },
        ),
    ]
