# Generated by Django 5.0.7 on 2024-07-30 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_alter_officialappointment_options_employee_isflagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffauditemployee',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staffauditemployee',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.bank'),
        ),
        migrations.AlterField(
            model_name='staffauditemployee',
            name='pfa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.pfa'),
        ),
    ]
