# Generated by Django 5.0.7 on 2024-07-30 11:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_alter_staffauditemployee_accountnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='educationInfoUpdated',
            new_name='isEducationInfoUpdated',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employmentInfoUpdated',
            new_name='isEmploymentInfoUpdated',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nextOfKinUpdated',
            new_name='isNextOfKinUpdated',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='personalInfoUpdated',
            new_name='isPersonalInfoUpdated',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='spouseInfoUpdated',
            new_name='isSpouseInfoUpdated',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nok1_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nok1_fullName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nok1_phoneNumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nok1_relationship',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nok2_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nok2_fullName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nok2_phoneNumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nok2_relationship',
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nok1_fullName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin 1 Full Name')),
                ('nok1_relationship', models.CharField(blank=True, choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Next of Kin 1 Relationship')),
                ('nok1_address', models.TextField(blank=True, null=True, verbose_name='Next of Kin 1 Address')),
                ('nok1_phoneNumber', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^(080|081|090|091|070)\\d{8}$')], verbose_name='Next of Kin 1 Phone Number')),
                ('nok2_fullName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin 2 Full Name')),
                ('nok2_relationship', models.CharField(blank=True, choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Next of Kin 2 Relationship')),
                ('nok2_address', models.TextField(blank=True, null=True, verbose_name='Next of Kin 2 Address')),
                ('nok2_phoneNumber', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^(080|081|090|091|070)\\d{8}$')], verbose_name='Next of Kin 2 Phone Number')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nextOfKin', to='hr_app.employee')),
            ],
            options={
                'verbose_name': 'Next of Kin',
                'verbose_name_plural': 'Next of Kin',
            },
        ),
    ]
