# Generated by Django 5.0.7 on 2024-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_staffauditemployee_isprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isPreviousEmploymentUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
