# Generated by Django 5.0.7 on 2024-07-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0010_employee_ispreviousemploymentupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationandtraining',
            name='fieldOfStudy',
            field=models.CharField(default='', max_length=50, verbose_name='Field of Study'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationandtraining',
            name='title',
            field=models.CharField(help_text='Title of the degree, certification, or course, \n(e.g. Primary School Ceritificate, SSCE, WAEC, GCE, BSC, BA, B.Ed', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.ImageField(blank=True, help_text='Please Upload your passport photo here', null=True, upload_to='employee_passports/', verbose_name='Passport Photo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residentialAddress',
            field=models.CharField(blank=True, max_length=150, verbose_name='Residential Address'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='nok1_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Next of Kin 1 Address'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='nok2_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Next of Kin 2 Address'),
        ),
    ]
