# Generated by Django 5.0.7 on 2024-07-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0013_discrepancy_resolution_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employeesLgaPosting', to='hr_app.lga', verbose_name='Station'),
        ),
    ]
