# Generated by Django 5.0.7 on 2024-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0018_employee_cadre_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dateOfBirth_ippis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dateOfFirstAppointment_ippis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='firstName_ippis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='middleName_ippis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname_ippis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
