# Generated by Django 5.0.7 on 2024-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0019_employee_dateofbirth_ippis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffauditemployee',
            name='residentialAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dateOfFirstAppointment_ippis',
            field=models.DateField(blank=True, null=True, verbose_name='IPPIS Date of First Appointment'),
        ),
    ]
