# Generated by Django 5.0.7 on 2024-08-06 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0022_employee_nok1_address_employee_nok1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffauditemployee',
            name='emailAddress',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='pfa',
            field=models.ForeignKey(blank=True, help_text='Please select the staff PFA', null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_app.pfa', verbose_name='Pension Fund Administrator'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pfaNumber',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$')], verbose_name='PFA PEN'),
        ),
    ]
