# Generated by Django 5.0.7 on 2024-08-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0023_staffauditemployee_emailaddress_alter_employee_pfa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffauditemployee',
            name='nok1_relationship',
            field=models.CharField(blank=True, choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Next of Kin 1 Relationship'),
        ),
        migrations.AlterField(
            model_name='staffauditemployee',
            name='nok2_relationship',
            field=models.CharField(blank=True, choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Next of Kin 2 Relationship'),
        ),
    ]
