# Generated by Django 5.1 on 2024-08-08 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0027_alter_employee_nok1_relationship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='isEducationInfoApproved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isEmploymentInfoApproved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isFinancialInfoApproved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isNextOfKinInfoApproved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isPassportApproved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isPersonalInfoApproved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isPreviousEmploymentApproved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isSpouseInfoApproved',
        ),
        migrations.AddField(
            model_name='employee',
            name='hasNameChanged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='isTransferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='nameChangeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='previousFirstName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requsted First Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='previousLastName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requsted Surname'),
        ),
        migrations.AddField(
            model_name='employee',
            name='previousMiddleName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requsted Middle Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='previousStateOfPosting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_state_employees', to='hr_app.state', verbose_name='State Transferred From'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transferDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Transfer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dateOfBirth_ippis',
            field=models.DateField(blank=True, null=True, verbose_name='IPPIS Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstName_ippis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IPPIS First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middleName_ippis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IPPIS Middle Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nok1_phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Next of Kin 1 Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nok2_phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Next of Kin 2 Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^(080|081|090|091|070)\\d{8}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname_ippis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IPPIS Surname'),
        ),
    ]
